server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于和binding进行绑定
          type: rabbit #该binder使用的消息队列类型  可为rabbit 和kafka
          environment: #rabbitmq相关的环境配置
            spring:
              rabbitmq:
                host: 172.16.81.31
                port: 5672
                username: guest
                password: guest
      bindings: #服务整合处理 将binder和消息队列进行绑定
        output: #表示这是一个消息的生产者（发送消息） 与之对应的是intput
          destination: studyExchange #表示要使用的exchange名称定义
          content-type: application/json #设置消息类型 本次为json  可以设置为文本（text/plain）
          binder: defaultRabbit #设置要绑定的消息服务的具体配置
eureka:
  client: #客户端进行eureka注册配置
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 5 #
    instance-id: send-8801.com #信息列表显示的主机名
    prefer-ip-address: true #访问路径变为ip地址
