server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心中动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh_lb #路由的id号 没有统一规则 但是必须唯一  可以随便写  但是建议符合服务名
#          uri: http://localhost:8001 #匹配后 提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后 提供服务的路由地址  lb://eureka中注册的服务名
          predicates:
            - Path=/payment/lb/** #断言  请求路径符合该断言则进行路由 可以有多个不同类型的  但是不要有多个同一类型的 如多个path

        - id: payment_routh_get #路由的id号 没有统一规则 但是必须唯一  可以随便写  但是建议符合服务名
#          uri: http://localhost:8001 #匹配后 提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后 提供服务的路由地址
          predicates:
              - Path=/payment/get/** #断言  请求路径符合该断言则进行路由 可以有多个不同类型的  但是不要有多个同一类型的 如多个path
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #集群版搭建方式
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #单机版配置
      defaultZone: http://eureka7001.com:7001/eureka